spring:
  profiles:
    active: dev

---
server:
  port: 8020
spring:
  profiles: dev
  application:
    name: springcloud-client-8020
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

---
server:
  port: 8021
spring:
  profiles: test
  application:
    name: springcloud-client-8021
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka